# Generated by Django 5.2.12 on 2026-03-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='resident',
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='Complaint', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
