# Generated by Django 4.2.11 on 2026-03-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('dry', 'Dry Waste'), ('wet', 'Wet Waste'), ('ewaste', 'E-Waste')], max_length=20)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
