# Generated by Django 5.2.12 on 2026-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='waste_type',
        ),
        migrations.AddField(
            model_name='pickup',
            name='item',
            field=models.CharField(choices=[('ampoules', 'Ampoules'), ('vials', 'Medicine Vials'), ('blades', 'Blades'), ('needles', 'Needles'), ('scalpels', 'Scalpels'), ('catheters', 'Catheters'), ('gloves', 'Gloves'), ('intravenous_tubes', 'Intravenous Tubes'), ('tubing', 'Tubing'), ('urine_bags', 'Urine Bags'), ('kids_diaper', 'Kids Diaper'), ('adult_diaper', 'Adult Diaper'), ('sanitary_pad', 'Sanitary Pad'), ('medical_waste', 'Medical Waste'), ('discreet', 'Discreet Waste'), ('hair', 'Hair')], default='ampoules', max_length=50),
            preserve_default=False,
        ),
    ]
