# Generated by Django 5.2.12 on 2026-03-05 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
