# Generated by Django 4.2.11 on 2026-03-09 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickup', '0003_remove_pickup_waste_type_pickup_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickup',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pickup',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickup',
            name='waste_type',
            field=models.CharField(choices=[('dry', 'Dry'), ('wet', 'Wet'), ('e-waste', 'E-Waste'), ('biomedical', 'Biomedical')], default='dry', max_length=20),
        ),
        migrations.AddField(
            model_name='pickup',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
