# Generated by Django 5.2.12 on 2026-03-17 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0004_pickup_assigned_worker_pickup_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Pickup Slot',
                'verbose_name_plural': 'Pickup Slots',
            },
        ),
        migrations.AddField(
            model_name='pickup',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='pickup.pickupslot'),
        ),
    ]
