# Generated by Django 5.2.12 on 2026-03-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0006_spatialtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpatialTest',
        ),
    ]
