# Generated by Django 5.2.12 on 2026-03-24 05:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0008_spatialtest'),
        ('users', '0009_ward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.AddField(
            model_name='pickup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pickup',
            name='qr_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ward'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pickup',
            index=models.Index(fields=['ward', 'scheduled_date', 'status'], name='pickup_pick_ward_id_36c5de_idx'),
        ),
    ]
