# Generated by Django 5.2.12 on 2026-03-24 06:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0009_rename_date_pickup_scheduled_date_and_more'),
        ('users', '0009_ward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateField()),
                ('planned_path', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('actual_path', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('hks_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ward')),
            ],
            options={
                'indexes': [models.Index(fields=['hks_worker', 'route_date'], name='pickup_rout_hks_wor_c2f1e0_idx')],
            },
        ),
    ]
