# Generated by Django 5.2.12 on 2026-03-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0010_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpatialTest',
        ),
    ]
