# Generated by Django 5.2.9 on 2026-03-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_latitude_user_longitude_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident'), ('hks_worker', 'HKS Worker'), ('recycler', 'Recycler'), ('driver', 'Driver')], default='resident', max_length=20),
        ),
    ]
